import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import KFold

from core.trainer import DeepPLIV
from utils.helpers import plot_boxplot
from skopt.callbacks import EarlyStopper
from skopt import gp_minimize
from skopt.space import Real
from skopt.utils import use_named_args
import optuna

class SimDataCreatorHighDimension:
    def __init__(self,
                 n: int,
                 p: int,
                 beta_1: float,
                 beta_2: float,
                 beta_3: float,
                 beta_u: float,
                 gamma_u: float,
                 non_null_iv: int,
                 gamma_iv: float):
        """
        Initialize the SimDataCreatorHighDimension class.

        :param n: int, number of samples.
        :param p: int, number of features.
        :param beta_1: float, coefficient for the endogenous variable.
        :param beta_2: float, coefficient for the exogenous variable.
        :param beta_3: float, coefficient for the interaction term between the endogenous and exogenous variables.
        :param beta_u: float, coefficient for the confounding variable.
        :param gamma_u: float, coefficient for the confounding variable.
        :param non_null_iv: int, indices of the non-null instrumental variables.
        """
        self.n = n
        self.p = p
        self.beta_1 = beta_1
        self.beta_2 = beta_2
        self.beta_3 = beta_3
        self.beta_u = beta_u
        self.gamma_u = gamma_u
        self.non_null_iv = non_null_iv

        self.gamma_iv = np.zeros(p)
        self.coef = np.random.normal(0, 1 / np.sqrt(self.n), p)
        self.u = np.random.normal(0, 1, n)
        self.g_iv = np.random.binomial(2, 0.3, size=(n, p)) - np.mean(np.random.binomial(2, 0.3, size=(n, p)), axis=0)
        self.g = np.random.binomial(2, 0.3, size=n) - np.mean(np.random.binomial(2, 0.3, size=n))
        self.strong_indicator = np.random.choice(self.p, self.non_null_iv, replace=False)
        self.weak_indicator = np.setdiff1d(np.arange(self.p), self.strong_indicator)

        self._generate_gamma_iv(gamma_iv)
        self.x_df = self._generate_x_df()
        self.y_df = self._generate_y_df()


    def _generate_gamma_iv(self, coef):
        self.gamma_iv[self.strong_indicator] = self.coef[self.strong_indicator] + coef
        self.gamma_iv[self.weak_indicator] = np.random.normal(0, 1 / np.sqrt(self.n),
                                                              size=self.p - self.non_null_iv)

    @staticmethod
    def _standardize(x):
        return x-x.mean() / x.std()

    def _generate_x_df(self):
        x_base = self.g_iv @ self.gamma_iv + self.gamma_u * self.u + np.random.normal(0, 1, self.n)
        x_scenario_1 = self._standardize(x_base)
        x_non_linear_1 = ((self.g_iv-1) ** 2) @ self.gamma_iv + self.gamma_u * self.u + np.random.normal(0, 1, self.n)
        x_scenario_2 = self._standardize(x_non_linear_1)
        x_non_linear_2 = np.abs(self.g_iv-1.5) @ self.gamma_iv + self.gamma_u * self.u + np.random.normal(0, 1, self.n)
        x_scenario_3 = self._standardize(x_non_linear_2)
        x_scenario_4 = self._standardize(x_base + (self.g_iv[:, :2] * self.g_iv[:, :2]).sum(axis=1) + self.g_iv[:, 2] * self.g_iv[:, 3])
        x_scenario_5 = self._standardize(x_base + self.g_iv[:, 2] * self.g_iv[:, 3] +
                                             ((self.g_iv[:, 0] < (-0.5)) | (self.g_iv[:, 1] < (-0.5))).astype(int)
                                             - ((self.g_iv[:, 0] > 0.5) & (self.g_iv[:, 1] > 0.5)).astype(int))
        return pd.DataFrame(np.concatenate((x_scenario_1.reshape(-1, 1),
                                            x_scenario_2.reshape(-1, 1),
                                            x_scenario_3.reshape(-1, 1),
                                            x_scenario_4.reshape(-1, 1),
                                            x_scenario_5.reshape(-1, 1)), axis=1),
                            columns=['x_scenario_1', 'x_scenario_2', 'x_scenario_3', 'x_scenario_4', 'x_scenario_5'])

    def _generate_y_df(self):
        y_base = self.beta_2 * self.g + self.beta_u * self.u + np.random.normal(0, 1, self.n)

        def aux_generate_y(x):
            return self.beta_1 * x + y_base + self.beta_3 * (self.g * x)

        y_df = self.x_df.apply(lambda x: aux_generate_y(x))
        y_df.columns = [f'y_scenario_{i + 1}' for i in range(5)]
        return y_df

    def get_data(self):
        """
        Get the data generated by the class. The data is in the form of a pandas DataFrame. The columns are as follows:
        - x_scenario_1: the data for scenario 1.
        - x_scenario_2: the data for scenario 2.
        - x_scenario_3: the data for scenario 3.
        - x_scenario_4: the data for scenario 4.
        - x_scenario_5: the data for scenario 5.
        - y_scenario_1: the outcome for scenario 1.
        - y_scenario_2: the outcome for scenario 2.
        - y_scenario_3: the outcome for scenario 3.
        - y_scenario_4: the outcome for scenario 4.
        - y_scenario_5: the outcome for scenario 5.
        - g_iv: the instrumental variables.
        - g: exogenous variable.
        :return: tuple of pd.DataFrame, the generated data.
        """
        return self.x_df, self.y_df, self.g_iv, self.g

class NaiveSRISPSHighDimension:
    def __init__(self, data_creator: SimDataCreatorHighDimension, scenario: int = 1):
        """
        Initialize the NaiveSRISPSHighDimension class.
        :param data_creator: SimDataCreatorHighDimension, an instance of the SimDataCreatorHighDimension class.
        :param scenario: int, the scenario to consider.
        """
        self.data_creator = data_creator
        self.x_df, self.y_df, self.g_iv, self.g = data_creator.get_data()
        self.x = self.x_df.iloc[:, [scenario-1]].values
        self.y = self.y_df.iloc[:, [scenario-1]].values

    def estimate_naive_regression(self):
        """
        Estimate the Naive SR-IV model using a simple linear regression model.
        :return: np.array, the coefficients of the Naive SR-IV model.
        """
        x = np.concatenate((self.x, self.g.reshape(-1, 1), self.x * self.g.reshape(-1, 1)), axis=1)
        y = self.y
        model = LinearRegression()
        model.fit(x, y)
        return model.coef_

    def get_first_and_second_stage_x_data(self):
        """
        Get the data for the first stage of the 2SLS model.
        :return: tuple of np.array, the data for the first and second stages of the 2SLS model.
        """
        half_n = self.x.shape[0] // 2
        x_first_stage, x_second_stage = self.x[:half_n], self.x[half_n:]
        vars_first_stage, vars_second_stage = self.g_iv[:half_n], self.g_iv[half_n:]

        return vars_first_stage, x_first_stage, vars_second_stage, x_second_stage

    def estimate_sps(self):
        """
        Estimate the 2SLS model using a simple linear regression model. - SPS
        :return: np.array, the coefficients of the Naive SR-IV model.
        """
        half_n = self.x.shape[0] // 2
        vars_first_stage, x_first_stage, vars_second_stage, x_second_stage = self.get_first_and_second_stage_x_data()

        model = LinearRegression()
        model.fit(vars_first_stage, x_first_stage)
        x_predicted = model.predict(vars_second_stage)
        x = np.concatenate((x_predicted, self.g[half_n:].reshape(-1, 1), x_predicted * self.g[half_n:].reshape(-1, 1)), axis=1)
        y = self.y[half_n:]
        model = LinearRegression()
        model.fit(x, y)
        return model.coef_

    def estimate_sri(self):
        """
        Estimate the 2SLS model using a simple linear regression model - SRI
        :return: np.array, the coefficients of the Naive SR-IV model.
        """
        half_n = self.x.shape[0] // 2
        vars_first_stage, x_first_stage, vars_second_stage, x_second_stage = self.get_first_and_second_stage_x_data()
        model = LinearRegression()
        model.fit(vars_first_stage, x_first_stage)
        x_predicted = model.predict(vars_second_stage)
        x_error = x_second_stage - x_predicted

        x = np.concatenate((x_second_stage, self.g[half_n:].reshape(-1, 1), x_second_stage * self.g[half_n:].reshape(-1, 1), x_error), axis=1)
        y = self.y[half_n:]
        model = LinearRegression()
        model.fit(x, y)
        return model.coef_

    def estimating_sri_sps_with_nn(self,
                                   epochs=2000,
                                   learning_rate = 0.01,
                                   l1_lambda = None):
        """
        Estimate the 2SLS model using a simple neural network model. - SPS
        :param epochs: int, the number of epochs for training the first stage.
        :param learning_rate: float, the learning rate for training the first stage.
        :return: tuple of np.array, the coefficients of the Naive SR-IV model.
        """
        half_n = self.x.shape[0] // 2
        vars_first_stage, x_first_stage, vars_second_stage, x_second_stage = self.get_first_and_second_stage_x_data()
        model = DeepPLIV()
        x_first_stage_standardized = (x_first_stage - x_first_stage.mean()) / x_first_stage.std()
        vars_first_stage_standardized = (vars_first_stage - vars_first_stage.mean()) / vars_first_stage.std()
        vars_second_stage_standardized = (vars_second_stage - vars_second_stage.mean()) / vars_second_stage.std()
        x_second_stage_standardized = (x_second_stage - x_second_stage.mean()) / x_second_stage.std()
        first_stage_model = model.fit_first_stage(x_first_stage_standardized, vars_first_stage_standardized,
                                                  epochs_first_stage=epochs,
                                                  learning_rate_first_stage=learning_rate,
                                                  l1_lambda = l1_lambda,
                                                  validation_data = (vars_second_stage_standardized,
                                                                     x_second_stage_standardized))
        if l1_lambda is None:
            l1_lambda =model.first_stage_model.l1_lambda
        x_predicted = first_stage_model.predict(vars_second_stage) * x_first_stage.std() + x_first_stage.mean()
        x_error = x_second_stage - x_predicted

        # SRI model
        x_sri = np.concatenate((x_second_stage, self.g[half_n:].reshape(-1, 1), x_second_stage * self.g[half_n:].reshape(-1, 1), x_error), axis=1)
        y = self.y[half_n:]
        model_sri = LinearRegression()
        model_sri.fit(x_sri, y)

        # SPS model
        x_sps = np.concatenate((x_predicted, self.g[half_n:].reshape(-1, 1), x_predicted * self.g[half_n:].reshape(-1, 1)), axis=1)
        model_sps = LinearRegression()
        model_sps.fit(x_sps, y)

        return model_sri.coef_, model_sps.coef_, l1_lambda


def run_high_dimension_genetic_simulation(num_simulations=10,
                                          beta_u: float =0,
                                          beta_3: float=0,
                                          beta_2: float=0.5,
                                          beta_1: float=1,
                                          scenario =1,
                                          n = 5000,
                                          p = 1000,
                                          gamma_iv = 0.1,
                                          gamma_u = 1,
                                          non_null_iv = 20,
                                          learning_rate = 0.01,
                                          epochs = 2000,
                                          l1_lambda = None):
    """
    Run the genetic simulation for the high-dimensional case.
     The simulation generates data using the SimDataCreatorHighDimension class
     and estimates the Naive SR-IV, SPS, and SRI models.
    :param num_simulations: parameter to control the number of simulations.
    :param beta_u: parameter to control the coefficient for the confounding variable.
    :param beta_3: parameter to control the coefficient for the interaction term between
    the endogenous and exogenous variables.
    :param beta_2: parameter to control the coefficient for the exogenous variable.
    :param beta_1: parameter to control the coefficient for the endogenous variable.
    :param scenario: parameter to control the scenario to consider.
    :param n: parameter to control the number of samples.
    :param p: parameter to control the number of features (in the first stage).
    :param gamma_iv: parameter to control the coefficient for the instrumental variables.
    :param gamma_u: parameter to control the coefficient for the confounding variable.
    :param non_null_iv: parameter to control the number of non-null instrumental variables.
    :param learning_rate: parameter to control the learning rate for the neural network model.
    :param epochs: parameter to control the number of epochs for training the neural network model.
    :return: pd.DataFrame, the results of the simulation.
    """
    results = {
        'method': [],
        'coefficient': [],
        'value': []
    }


    for _ in range(num_simulations):
        data_creator = SimDataCreatorHighDimension(n=n, p=p, beta_1=beta_1, beta_2=beta_2, beta_3=beta_3, beta_u=beta_u,
                                                   gamma_u=gamma_u, non_null_iv=non_null_iv, gamma_iv=gamma_iv)

        naive_srisps = NaiveSRISPSHighDimension(data_creator=data_creator, scenario=scenario)
        coefficients = naive_srisps.estimate_naive_regression()
        for i, coef in enumerate(coefficients[0]):
            results['method'].append('Naive Regression')
            results['coefficient'].append(f'coef_{i}')
            results['value'].append(coef)

        coefficients = naive_srisps.estimate_sps()
        for i, coef in enumerate(coefficients[0]):
            results['method'].append('SPS')
            results['coefficient'].append(f'coef_{i}')
            results['value'].append(coef)

        coefficients = naive_srisps.estimate_sri()
        for i, coef in enumerate(coefficients[0]):
            results['method'].append('SRI')
            results['coefficient'].append(f'coef_{i}')
            results['value'].append(coef)
        # NN model
        coefficients_sri, coefficients_sps, l1_lambda = naive_srisps.estimating_sri_sps_with_nn(learning_rate=learning_rate,
                                                                                     epochs = epochs,
                                                                                     l1_lambda = l1_lambda)
        for i, coef in enumerate(coefficients_sri[0]):
            results['method'].append('SRI with NN')
            results['coefficient'].append(f'coef_{i}')
            results['value'].append(coef)
            if i == 0:
                print(f'coef_{i} sri: {coef}')
        for i, coef in enumerate(coefficients_sps[0]):
            results['method'].append('SPS with NN')
            results['coefficient'].append(f'coef_{i}')
            results['value'].append(coef)
            if i == 0:
                print(f'coef_{i} sps: {coef}')

    results_df = pd.DataFrame(results)
    results_df.to_pickle(f'high_dim_sim_results_{num_simulations}_{beta_u}_{beta_3}_{scenario}.pkl')
    return results_df

if __name__ == '__main__':
    lr = 0.001
    num_simulations: int = 500
    beta_2: float = 1
    beta_1: float = -1
    scenario: int = 2
    n: int = 20000
    p: int = 1000
    gamma_iv : float = 0.05
    gamma_u : float = 1
    epochs : int = 4000
    non_null_iv: int = 100
    for beta_u_ in [1]:
        for beta_3_ in [0.5]:
            res = run_high_dimension_genetic_simulation(num_simulations=num_simulations,
                                                  beta_u=beta_u_,
                                                  beta_3=beta_3_,
                                                  scenario=scenario,
                                                  p=p,
                                                  n=n,
                                                  beta_1=beta_1,
                                                  beta_2=beta_2,
                                                  gamma_iv=gamma_iv,
                                                  gamma_u=gamma_u,
                                                  non_null_iv = non_null_iv,
                                                  learning_rate=lr,
                                                  epochs = epochs)
    plot_boxplot(res, y_line=beta_1)